"""init

Revision ID: 45a356fdb764
Revises: 
Create Date: 2025-02-09 13:57:30.317596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '45a356fdb764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_table('offices',
    sa.Column('office_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_index(op.f('ix_offices_office_id'), 'offices', ['office_id'], unique=False)
    op.create_index(op.f('ix_offices_org_id'), 'offices', ['org_id'], unique=True)
    op.create_table('works',
    sa.Column('work_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_index(op.f('ix_works_category_id'), 'works', ['category_id'], unique=False)
    op.create_index(op.f('ix_works_org_id'), 'works', ['org_id'], unique=False)
    op.create_index(op.f('ix_works_work_id'), 'works', ['work_id'], unique=False)
    op.create_table('geo',
    sa.Column('geo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False, comment='WGS84'),
    sa.ForeignKeyConstraint(['office_id'], ['offices.office_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geo_id')
    )
    # op.create_index('idx_geo_geog', 'geo', ['geog'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geo_geo_id'), 'geo', ['geo_id'], unique=False)
    op.create_index(op.f('ix_geo_office_id'), 'geo', ['office_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_office_id'), table_name='geo')
    op.drop_index(op.f('ix_geo_geo_id'), table_name='geo')
    op.drop_index('idx_geo_geog', table_name='geo', postgresql_using='gist')
    op.drop_table('geo')
    op.drop_index(op.f('ix_works_work_id'), table_name='works')
    op.drop_index(op.f('ix_works_org_id'), table_name='works')
    op.drop_index(op.f('ix_works_category_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_offices_org_id'), table_name='offices')
    op.drop_index(op.f('ix_offices_office_id'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
