"""add phone

Revision ID: 26377238d2ed
Revises: 45a356fdb764
Create Date: 2025-02-09 15:05:38.346698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '26377238d2ed'
down_revision: Union[str, None] = '45a356fdb764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('phone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_index(op.f('ix_phones_org_id'), 'phones', ['org_id'], unique=False)
    op.create_index(op.f('ix_phones_phone_id'), 'phones', ['phone_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_phones_phone_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_org_id'), table_name='phones')
    op.drop_table('phones')
    # ### end Alembic commands ###
